id: P007880
initial_creation_type: ocr
source_metadata:
  id: bdr:W23906
  title: དུས་འཁོར་ཉེར་མཁོའི་ཆོས་ཚན་ཁག
  author: ''
  volumes:
    60198237570041ad86f4720e57b53df8:
      image_group_id: I3206
      title: ''
      volume_number: 1
      total_pages: 365
ebook_metadata:
  title: དུས་འཁོར་ཉེར་མཁོའི་ཆོས་ཚན་ཁག
  author: ''
  sku: P007880
  cover: cover.jpg
  layers:
  - pagination
