id: P007880
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:54.139303
source_metadata:
  id: bdr:W23906
  title: དུས་འཁོར་ཉེར་མཁོའི་ཆོས་ཚན་ཁག
  author: ''
  volumes:
    60198237570041ad86f4720e57b53df8:
      image_group_id: I3206
      title: ''
      volume_number: 1
      total_pages: 365
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
